services:
  pez:
    build:
      context: .
      dockerfile: Dockerfile
    image: pez_humble:latest
    container_name: pez_humble
    network_mode: host
    volumes:
      # Bind-mount your workspace
      - ./pez_ws:/pez_ws
    devices:
      - "/dev/input:/dev/input"
    stdin_open: true   # keep STDIN open (so you get a shell)
    tty: true          # allocate a TTY

    # The image's ENTRYPOINT sources ROS and your workspace,
    # and defaults to `bash`—so `docker-compose up` leaves you at a shell.
