# Fish‐side communications: decode incoming Packet A/B and drive teleop + camera

modem_io:
  port: '/dev/ttyModem0'
  baud: 9600
  timeout: 0.1

# Expose the port as a ROS param so we can remap at runtime if needed
parameters:
  port: '/dev/ttyModem0'

# No outbound schedules/triggers/publishers/services here—
# everything is handled in the fish_side plugin via inbound decoding.

serial_handlers: []     # not used (plugin does its own loop)

schedules: []
triggers: []
publishers: []
services: []

plugins:
  - module: pez_comms.plugins.fish_side
    config:
      port_param:      port
      baud:            9600
      timeout:         0.1
      packet_a:        A_NORMAL
      packet_b:        B_COMMAND
      topic_cmd_vel:   /pez/cmd_vel
      topic_camera:    /pez/camera_control
      service_map:
        "0": /teleoperation/start_swim
        "1": /teleoperation/toggle_magnet
        "2": /teleoperation/toggle_neutral
      camera_svc_id:   3
