# guide_config.yaml
#
# Master configuration template for the `comms` node (pez_comms).
# Copy this into config/, rename to your profile (e.g. fish_comms.yaml),
# and edit only the sections you need.  Load it via:
#   ros2 launch pez_comms comms_launch.py config_file:=config/guide_config.yaml
#

pez_comms:
  ros__parameters:

    #################################################################
    # 1) MODEM I/O SETTINGS
    #################################################################
    modem_io:
      port: "/dev/ttyUSB0"     # serial device or pseudo-TTY
      baud: 9600               # UART speed
      timeout: 0.1             # seconds to wait on reads

    #################################################################
    # 2) GENERAL PARAMETERS
    #################################################################
    # Any scalar params you want exposed as `param:…` in your encode blocks
    x:  0.0
    y:  0.0
    z:  0.0
    # e.g. for snapshots:
    # snapshot_topic: "/my_snapshot_topic"

    #################################################################
    # 3) SCHEDULED PACKET STREAMS
    #################################################################
    # Time-based sequences of packet sends:
    schedules:
      - name: drive_loop
        loop: true
        steps:
          - name: send_A
            duration: 0.25
            encode:
              type: A_NORMAL
              x:   param:x
              y:   param:y
              z:   param:z

          # - name: wait_for_flag
          #   wait_for_param: my_flag

    #################################################################
    # 4) TOPIC-TRIGGERED PACKETS
    #################################################################
    triggers:
      - subscribe:
          topic: "/user_cmd"
          type: "std_msgs/msg/String"
          qos: 10
        encode:
          type: B_COMMAND
          value: msg.data

    #################################################################
    # 5) PARAMETER-DRIVEN PUBLISHERS
    #################################################################
    publishers:
      - topic: "/heartbeat"
        type: "std_msgs/msg/Empty"
        rate: 1.0

    #################################################################
    # 6) SERVICE-BASED PACKET SENDERS
    #################################################################
    services:
      - name: "/do_magic"
        srv_type: "std_srvs/srv/Trigger"
        on_request:
          encode:
            type: MAGIC_PACKET
            level: param:magic_level
        on_response:
          publish:
            topic: "/magic_done"
            type: "std_msgs/msg/Bool"
            value: resp.success

    #################################################################
    # 7) INBOUND PACKET HANDLERS
    #################################################################
    serial_handlers:
      - packet: A_NORMAL
        decode:
          x_q: x_q
          y_q: y_q
          z_q: z_q
        publish:
          topic: "/pez/cmd_vel"
          type: "geometry_msgs/msg/Twist"
          mapping:
            linear.x: "dequant(x_q,3)"
            linear.y: "dequant(y_q,2)"
            linear.z: "dequant(z_q,2)"

      - packet: B_COMMAND
        decode:
          service_id: service_id
          value:      value
          seq:        seq
        service_map:
          "0": "/teleoperation/start_swim"
          "1": "/teleoperation/toggle_magnet"
          "2": "/teleoperation/toggle_neutral"
        special:
          "3":
            publish:
              topic: "/pez/camera_control"
              type: "std_msgs/msg/Float32"
              expr: "1.0 if value == 1 else -1.0"

    #################################################################
    # 8) PLUGINS
    #################################################################
    plugins:
      - module: pez_comms.plugins.fish_side
        config:
          port_param:    modem_io.port
          baud:          9600
          timeout:       0.1
          packet_a:      A_NORMAL
          packet_b:      B_COMMAND
          topic_cmd_vel: /pez/cmd_vel
          topic_camera:  /pez/camera_control
          service_map:
            "0": /teleoperation/start_swim
            "1": /teleoperation/toggle_magnet
            "2": /teleoperation/toggle_neutral
          camera_svc_id: 3

      - module: pez_comms.plugins.host_side
        config:
          packet_a:        A_NORMAL
          packet_b:        B_COMMAND
          topic_cmd_vel:   /pez/cmd_vel
          topic_camera:    /pez/camera_control
          services:
            "0": /teleoperation
            "1": /teleoperation/toggle_magnet
            "2": /teleoperation/toggle_neutral
          camera_svc_id:   3
          broadcast_rate:  4.0
          ack_timeout:     2.0
          svc_wait:        5.0
