ros__parameters:
  modem_io:
    port: '/tmp/pez_fish'      # default serial port
    baud: 9600                  # default baud
    timeout: 0.1                # default read timeout

  # We aren’t using schedules/triggers/publishers/services for fish side:
  schedules:       []
  triggers:        []
  publishers:      []
  services:        []

  # The fish_side plugin does all inbound work itself
  serial_handlers: []

  plugins:
    - module: pez_comms.plugins.fish_side
      config:
        # This plugin reads the param 'modem_io.port' at runtime,
        # so port_param should match exactly:
        port_param:      modem_io.port
        baud:            9600
        timeout:         0.1
        packet_a:        A_NORMAL
        packet_b:        B_COMMAND
        topic_cmd_vel:   cmd_vel
        topic_camera:    camera_control
        service_map:
          "0": teleoperation/start_swim
          "1": teleoperation/toggle_magnet
          "2": teleoperation/toggle_neutral
        camera_svc_id:   3
