# ---------- factor-out the shared bits ------------------------------------
x-pez-common: &pez-common
  image: mapuigsari/pez:comms-arm64v8
  network_mode: host
  stdin_open: true
  tty: true
  restart: unless-stopped
  privileged: true           # full /dev pass-through
  volumes:
    - /dev:/dev
  environment:
    - ROS_DOMAIN_ID=21
    - LANG=C.UTF-8
    - LC_ALL=C.UTF-8

# ---------- each launch mode is its own service ---------------------------
services:
  pez-comms-dev:
    <<: *pez-common
    command: "dev" 
    container_name: pez_comms_dev
  pez-comms:
    <<: *pez-common
    command: "comms"          # ros2 launch pez_core joy_launch.py comms_flag:=true
    container_name: pez_comms

