# ---------- common settings everyone will inherit --------------------------
x-pez-common: &pez-common
  image: mapuigsari/pez:core-amd64
  network_mode: host
  volumes:
    - ../../pez_humble/pez_ws:/pez_ws:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - type: tmpfs        # runtime dir for Qt/X11
      target: /tmp/runtime-1000
      tmpfs: { mode: 0700 }
  devices:
    - "/dev:/dev"
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/ros/.Xauthority
    - XDG_RUNTIME_DIR=/tmp/runtime-1000
    - LIBGL_ALWAYS_SOFTWARE=1
    - QT_X11_NO_MITSHM=1
  stdin_open: true
  tty: true              # keeps an interactive shell open if you attach

# ---------- service variants ----------------------------------------------
services:
  pez-dev:
    <<: *pez-common
    container_name: pez_dev           # must be unique
    command: "dev"                    # leaves you in a bash shell

  pez-cable:
    <<: *pez-common
    container_name: pez_cable
    command: "cable"                  # ros2 launch pez_core joy_launch.py

  pez-comms:
    <<: *pez-common
    container_name: pez_comms
    command: "comms"                  # ros2 launch … comms_flag:=true
