# ---------- common settings everyone will inherit --------------------------
x-pez-common: &pez-common
  image: mapuigsari/pez:core-amd64
  network_mode: host
  volumes:
    - ../../pez_humble/pez_ws:/pez_ws:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - type: tmpfs        # runtime dir for Qt/X11
      target: /tmp/runtime-1000
      tmpfs: { mode: 0700 }
  devices:
    - "/dev/input/:/dev/input/"  # example for input device
    #- "dev/ttyUSB0:/dev/ttyUSB0"  # Comment this line if you don't need a serial device
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/ros/.Xauthority
    - XDG_RUNTIME_DIR=/tmp/runtime-1000
    - LIBGL_ALWAYS_SOFTWARE=1
    - QT_X11_NO_MITSHM=1
  stdin_open: true
  tty: true              # keeps an interactive shell open if you attach

# ---------- service variants ----------------------------------------------
services:
  pez-dev: # docker compose run --rm pez-dev
    <<: *pez-common
    container_name: pez_dev
    command: "dev" 

  pez-cable:  # docker compose up pez-cable 
    <<: *pez-common
    container_name: pez_cable
    command: "cable"                  

  pez-comms:  # docker compose up pez-comms
    <<: *pez-common
    container_name: pez_comms
    command: "pez_comms"                 

  bluerov-comms:  # docker compose up pez-comms
    <<: *pez-common
    container_name: bluerov_comms
    command: "blue_comms" 