# All times are offsets [s] from start-of-run ──────────────────────────────
cmd_vel:
  - {t: 1.0,  linear: {x:  0.0, y: 0.0, z: -1.0},  angular: {z: 0.0}}
  - {t: 6.0,  linear: {x:  0.0, y: 0.0, z: 0.0},  angular: {z: 0.0}}
  - {t: 11.0,  linear: {x:  0.0, y: 1.0, z: 0.0},  angular: {z: 0.0}}
  - {t: 16.0,  linear: {x: 0.0, y: 0.0, z: 0.0},  angular: {z: 0.0}}
  - {t: 21.0,  linear: {x:  0.0, y: -1.0, z: 0.0},  angular: {z: 0.0}}
  - {t: 26.0,  linear: {x:  0.0, y: 0.0, z: 0.0},  angular: {z: 0.0}}
  - {t: 31.0,  linear: {x:  0.0, y: 0.0, z: 1.0},  angular: {z: 0.0}}

services:
#  - {t: 0.0, service: pez/teleoperation/toggle_magnet, type: std_srvs/srv/Trigger}
  - {t: 0.0,  service: pez/teleoperation/swim_start,  type: std_srvs/srv/Trigger}
  - {t: 36.0, service: pez/teleoperation/swim_stop,   type: std_srvs/srv/Trigger}