name: Build & Push Multi-Arch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
  
      - name: Set up QEMU (for cross-build)
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build & push ARMv7 image
        uses: docker/build-push-action@v5
        with:
          context: .  
          file: docker_pez_ros/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: mapuigsari/pez-ros-noetic-nav:arm32v7