name: Build & Publish Multi-Arch Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # AMD64 job: build from pez_humble/Dockerfile, context=pez_ros/pez_humble, tag=:amd64
          - arch: linux/amd64
            context: .
            dockerfile: pez_ros/pez_docker/host/Dockerfile
            image_tag: core-amd64

          # ARM64v8 job: build from pez_docker/Dockerfile, context=pez_ros/pez_docker, tag=:arm64v8
          - arch: linux/arm64/v8
            context: .
            dockerfile: pez_ros/pez_docker/pez/Dockerfile
            image_tag: core-arm64v8

          - arch: linux/arm64/v8
            context: .
            dockerfile: pez_ros/pez_docker/comms/Dockerfile
            image_tag: comms-arm64v8

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU for cross-building
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.arch }} image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile }}
          platforms: ${{ matrix.arch }}
          push: true
          tags: mapuigsari/pez:${{ matrix.image_tag }}
